on:
  workflow_dispatch:

jobs:
  macos_x86_64:
    strategy:
      matrix:
        os: [macos-13]
        arch: [x86_64]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          mkdir deploy
          cd build
          cmake ..
          make
          cd ..
          cp build/mac/tests/openpnp-capture-test deploy/openpnp-capture-test-${{ matrix.os }}-${{ matrix.arch }}
          cp build/libopenpnp-capture.a deploy/libopenpnp-capture-${{ matrix.os }}-${{ matrix.arch }}.a

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with: 
          path: |
            deploy/*
  
  macos_arm64: 
    strategy:
      matrix:
        os: [macos-14]
        arch: [arm64]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          mkdir deploy
          cd build
          cmake ..
          make
          cd ..
          cp build/mac/tests/openpnp-capture-test deploy/openpnp-capture-test-${{ matrix.os }}-${{ matrix.arch }}
          cp build/libopenpnp-capture.a deploy/libopenpnp-capture-${{ matrix.os }}-${{ matrix.arch }}.a

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with: 
          path: |
            deploy/*

  windows_x86_64: 
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x86_64]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v2

      - name: Build
        run: |
          mkdir build
          mkdir deploy
          cd build
          cmake ..
          cmake --build . --config Release
          cd ..
          cp build/win/tests/Release/openpnp-capture-test.exe deploy/openpnp-capture-test-${{ matrix.os }}-${{ matrix.arch }}.exe
          cp build/Release/openpnp-capture.lib deploy/libopenpnp-capture-${{ matrix.os }}-${{ matrix.arch }}.lib

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with: 
          path: |
            deploy/*
